# Generated by Django 4.2 on 2025-12-07 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_scientificinterest_teacherprofile_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата підтвердження'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teachers', to=settings.AUTH_USER_MODEL, verbose_name='Підтверджено користувачем'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Підтверджено'),
        ),
    ]
