# Generated by Django 4.2 on 2025-11-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_scientificinterest_teacherprofile_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('is_filled', models.BooleanField(default=False, verbose_name='Зайнятий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_slot', to='profiles.studentprofile', verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='profiles.teacherprofile', verbose_name='Викладач')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='searching.slot', verbose_name='Слот')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_requests', to='profiles.studentprofile', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Запит на слот',
                'verbose_name_plural': 'Запити на слоти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='slotrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'slot'), name='unique_pending_request'),
        ),
    ]
