# Generated by Django 4.2 on 2025-12-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='topic',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Тема консультації'),
        ),
    ]
